[package]
name = "saltwater"
version = "0.11.0"
authors = [
  "Joshua Nelson <jyn514@gmail.com>",
  "Graham Scheaffer <me@gisch.dev>",
  "Wesley Norris <repnop@outlook.com>",
  "playX",
  "Kevin Becker <k.becker@byter.dev>",
  "Hunter Damron <hdamron@email.sc.edu>",
  "Justus K <justus.k@protonmail.com>",
]
edition = "2021"
description = "A C compiler written in Rust, with a focus on good error messages."
repository = "https://github.com/jyn514/saltwater/"
readme = "README.md"
categories = ["development-tools", "parser-implementations"]
license = "BSD-3-Clause"
keywords = ["C", "compiler", "recursive-descent", "cranelift"]
default-run = "swcc"
documentation = "https://docs.rs/saltwater"

[dependencies]
ansi_term = "0.12"
arcstr = "1.1"
tempfile = "3.9"
pico-args = { version = "0.5", features = ["short-space-opt"] }
color-backtrace = { version = "0.5", default-features = false, optional = true }
atty = { version = "0.2", default-features = false }
git-testament = { version = "0.2.5", optional = true }
cranelift = "0.66"
cranelift-module = "0.66"
cranelift-object = "0.66"
target-lexicon = "0.10"
lazy_static = "1.4"
hexponent = "0.3"
thiserror = "^1.0.56"
lasso = "0.7"
codespan = { version = "0.11", default-features = false }
counter = "0.5"
shared_str = "0.1.1"
time = {version="0.3", features = ["local-offset", "macros", "formatting", "std"]}
cranelift-codegen = { version = "0.66" }

[dev-dependencies]
env_logger = { version = "0.11", default-features = false }
log = "0.4.2"
criterion = "0.5"
walkdir = "2.4"
proptest = "^1.4"
proptest-derive = "0.4"

[features]
default = ["color-backtrace"]
# for internal use
_test_headers = []

[workspace]

[[bin]]
name = "swcc"
path = "src/main.rs"


[[test]]
name = "runner"

[[test]]
name = "varargs"

[[test]]
name = "headers"
# MacOS breaks if you pass -undef to the system preprocessor
required-features = ["_test_header"]

[profile.release]
lto = true

[profile.test]
debug = false  # speeds up link time

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false
codegen-units = 1
incremental = false
overflow-checks = false

[package.metadata.docs.rs]
all-features = true
# opt-out of non-default targets
targets = []
